<?php
/**
 *                    Jojo CMS
 *                ================
 *
 * Copyright 2007 Harvey Kane <code@ragepank.com>
 * Copyright 2007 Michael Holt <code@gardyneholt.co.nz>
 * Copyright 2007 Melanie Schulz <mel@gardyneholt.co.nz>
 *
 * See the enclosed file license.txt for license information (LGPL). If you
 * did not receive this file, see http://www.fsf.org/copyleft/lgpl.html.
 *
 * @author  Harvey Kane <code@ragepank.com>
 * @license http://www.fsf.org/copyleft/lgpl.html GNU Lesser General Public License
 * @link    http://www.jojocms.org JojoCMS
 */

class JOJO_Plugin_Jojo_simplecloak extends JOJO_Plugin
{

    function isAuthenticatedBot()
    {
        if (!defined('USE_CUSTOM_CONNECT_CODE')) define('USE_CUSTOM_CONNECT_CODE', 1);

        foreach (Jojo::listPlugins('external/simplecloak/simple_cloak_v2.inc.php') as $pluginfile) {
            require_once($pluginfile);
            break;
        }
        SimpleCloakV2::updateAll();
        $not_authenticated_bot = SimpleCloakV2::metaRobotsExcludeProxies(false);

        if ($not_authenticated_bot) {
            return false;
        } else {
            return true;
        }
    }

    function before_fetch_template()
    {
        if (Jojo::getOption('simplecloak_enabled') == 'no') return true;
        if (_SITEURI != '') return true; //only enabled for homepage

        global $smarty;

        if (!JOJO_Plugin_Jojo_simplecloak::isAuthenticatedBot()) {
            $smarty->assign('robots_index', false);
            $smarty->assign('robots_follow', false);
        }
    }

    function cached_content($html)
    {
        if (Jojo::getOption('simplecloak_enabled') == 'no') return $html;
        if (_SITEURI != '') return $html; //only enabled for homepage

        /* if the page has already been cached, we need to make sure we have the right tags on here */
        if (JOJO_Plugin_Jojo_simplecloak::isAuthenticatedBot()) {
            $html = ''; //clear the HTML so that it will be regenerated by Jojo
        } else {
            /* if the page has a meta robots tag */
            if (preg_match('%<meta name="robots" content=".*?" />%', $content)) {
    	        /* replace any robots tag with noindex, nofollow */
                $html = preg_replace('%<meta name="robots" content=".*?" />%', '<meta name="robots" content="noindex, nofollow" />', $html);
            } else {
                /* no robots tag - need to add one */
                $html = preg_replace('/<head>/', "<head>\r\n<meta name=\"robots\" content=\"noindex, nofollow\" />", $html);
            }
        }


        return $html;
    }
}